name: "🛡️ Validate Central CI/CD"

on: 
    pull_request:
        branches: [develop, main]
    push:
        branches: [develop]

jobs:
    yamllint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "Validate YAML files"
              uses: actionshub/yamllint@1.1.0
              with:
                file_or_dir: '.'

    docs:
        runs-on: ubuntu-latest
        steps:
            
            - uses: actions/checkout@v4
            
            - name: Validar Markdown
              uses: DavidAnson/markdownlint-cli2-action@v15