name: "🛡️ Validate Central CI/CD"

on: 
    pull_request:
        branches: [develop, main]
    push:
        branches: [develop]

jobs:
    yamlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "Validate YAML files"
              uses: biqlik/action-yamllint@v3

    lint-python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Setup Python"
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            
            - name: "Install linters"
              run: |
                python -m pip install --upgrade pip
                pip install flake8 black isort
            
            - name: "Run linters"
              run: |
                flake8 .
            
            - name: "Run Black"
              run: |
                black --check .
            
            - name: "Run Isort"
              run: |
                isort --check .

    docs:
        runs-on: ubuntu-latest
        steps:
            
            - uses: actions/checkout@v4
            
            - name: Validar Markdown
              uses: DavidAnson/markdownlint-cli2-action@v15